name = "ModuleTest"
uuid = "9c639127-7cbc-4713-a573-c017d9733fef"
authors = ["hzarei4 <hzoshtolagh@gmail.com>"]
version = "0.1.0"

[deps]
CenterIndexedArrays = "https://github.com/HolyLab/CenterIndexedArrays.jl"
InverseModeling = "https://github.com/RainerHeintzmann/InverseModeling.jl"
PSFDistiller = "https://github.com/bionanoimaging/PSFDistiller.jl"
